### ISSUE TITLE
Runtime error; arm-none-eabi toolchain

### ISSUE THREAD

**Issue by fouge** [ebs-universe/fpv-gcc#3]
Hello,

I tried to use your tool but stumbled upon an error, even with the latest version.
My map file was generated using `arm-none-eabi-ld`, is it compatible?

```
Runtime Error getting new node : .debug_macro.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.boards_c_o.....
```

I attached my map file, renamed in txt format to be sent here (please rename the file if needed).

[std_atoi.txt](https://github.com/chintal/fpv-gcc/files/3364362/std_atoi.txt)

Let me know, I really want to make it work :) 
Best,
Cyril

**Comment by chintal** [comment]
@fouge I haven't really tested against arm yet, though #2 suggests it should more or less work, or nearly so. I'll take a look at your mapfile and see what I see.

**Comment by chintal** [comment]
@fouge The file seems to work if you lop off the .debug_macro section entirely, specifically, remove everything in L698-765. The lines to remove are listed below. 

    .debug_macro    0x0000000000000000    0x1682e
      .debug_macro   0x0000000000000000      0x358 _build/nrf52840_xxaa/boards.c.o
      ...
      .debug_macro   0x00000000000161d7      0x16d _build/nrf52840_xxaa/boards.c.o
      .debug_macro   0x0000000000016344      0x3a5 _build/nrf52840_xxaa/main.c.o
      ...
      .debug_macro   0x000000000001671b       0x22 _build/nrf52840_xxaa/main.c.o
      .debug_macro   0x000000000001673d       0xf1 _build/nrf52840_xxaa/system_nrf52840.c.o

Once you do, the file is atleast processed

    $ fpvgcc std_atoi.txt --sar
    +--------------------------+-----+-------+-----------+-------+--------+
    | FILE                     | VEC | FLASH | *default* |   RAM |  TOTAL |
    +--------------------------+-----+-------+-----------+-------+--------+
    | boards.c.o               |     |   280 |    554649 |       | 554929 |
    | gcc_startup_nrf52840.S.o |     |   572 |        32 | 16384 |  16988 |
    | system_nrf52840.c.o      |     |  8504 |       897 |     4 |   9405 |
    | main.c.o                 |     |  5516 |      1200 |       |   6716 |
    | libc_nano.a              |     |   660 |       624 |   100 |   1384 |
    | crtbegin.o               |     |    64 |        52 |    36 |    152 |
    | crt0.o                   |     |   124 |        28 |       |    152 |
    | libnosys.a               |     |     4 |        84 |       |     88 |
    | crtend.o                 |     |     4 |        50 |       |     54 |
    | crtn.o                   |     |    16 |        30 |       |     46 |
    | crti.o                   |     |     8 |           |       |      8 |
    | TOTALS                   |   0 | 15752 |    557646 | 16524 |        |
    +--------------------------+-----+-------+-----------+-------+--------+

This is probably a manifestation of the problem that appears when there are duplicate object names in a build, which is an issue that remains unresolved. In this instance, though, it is breaking on the repeated  `_build/nrf52840_xxaa/boards.c.o` within the `.debug_macro` section, which itself is discarded anyway. fpvgcc should just ignore this section, perhaps, or have a cleaner way to disambiguate those repeated 'symbols'. I'll think of a way to handle the problem and will let you know when (if) an updated version is available without this issue.

In the meanwhile, take a look at the output, in any case. Make the change to your copy of the map file and see if it works for you. If the numbers looks generally accurate, let me know. I don't know if there are other issues with arm-none-eabi map files, so knowing that the overall numbers look reasonably accurate will help. I suspect there is a significant problem with the counting, will all the debug sections being counted in `*default*`. This is something I encountered in a recent version of msp430-elf-gcc, and some work will be needed to define a dialect for arm-none-eabi which helps fpvgcc throw out a lot of the discarded sections.

**Comment by chintal** [comment]
@fouge Please check with v0.9.0 (available from pypi) and let me know if your problem is resolved.

**Comment by fouge** [comment]
Hello,

Sorry for the very long delay...

I made it work on another project using arm-none-eabi toolchain, I think you can close the issue :)
Thanks for that tool

Best

**Comment by chintal** [comment]
Ok

For the record, to the best of my knowledge, there are no known outstanding serious issues with arm-none-eabi and fpvgcc.
